# Generated by Django 5.0.6 on 2024-07-14 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PosterinPag', '0002_boleta_categoria_producto_detalle_boleta'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_boleta',
            name='cliente',
            field=models.CharField(default='Prueba', max_length=200),
        ),
        migrations.AddField(
            model_name='detalle_boleta',
            name='descripcion_producto',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalle_boleta',
            name='nombre_producto',
            field=models.CharField(default='Prueba', max_length=200),
        ),
        migrations.AlterField(
            model_name='detalle_boleta',
            name='subtotal',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
